### PR TITLE
(MODULES-4275) Customize ACE YAML serialization

### PR DESCRIPTION
**Pull request by Iristyle**
- Ruby 2.3 has changed the behavior of YAML serialization so that
   Hash derived instances will serialize all of their instance
   variables per:

   https://github.com/ruby/ruby/commit/fe0414b5473b5332706126d2a017a9bf235c8146

   Psych used to produce an empty serialization of the ACE type in
   Ruby 2.1.9 like:

```yaml
   --- !ruby/hash:Puppet::Type::Acl::Ace {}
```

   In Ruby 2.3, it will produce something like this:

```yaml
   --- !ruby/hash-with-ivars:Puppet::Type::Acl::Ace
     elements: {}
     ivars:
       :@provider:
       :@identity: Administrators
       :@hash:
       :@id: S-32-12-0
       :@mask: '2023422'
       :@rights:
         - :full
       :@perm_type: :allow
       :@child_types: :all
       :@affects: :all
       :@is_inherited: false
```

  The issue that arises is that @provider is a Puppet provider
  instance that cannot be YAML serialized and will crash in 2 key
  situations during a Puppet run:

    * When the last_run_report.yaml is persisted
    * When corrective changes transaction reports are written

 - The solution is to implement the encode_with method on the ACE type
   to control what gets serialized. Since ACE already has a to_hash
   method, let it do the heavy lifting to produce the bare Hash
   structure for Psych to serialize.

   Note that nil is passed as the "tag" used by Pysch, which means
   that the key / value pairs are emitted as a bare YAML hash instead
   of the custom type:

```yaml
    --- !ruby/object:Puppet::Type::Acl::Ace
```

 - This should also more correctly fix a longstanding PE console issue
   described in PCP-542 where the master is unable to deserialize
   YAML strings like the following because the Ruby classes are not
   loaded on the master:

```yaml
   !ruby/hash:Puppet::Type::Acl::Ace {}
```

 - Also see PUP-7381 for other YAML serialization work proceeding
   within Puppe to address Ruby 2.3 related behavioral changes.

### CODE REVIEW

**Comment by joshcooper** [comment]
@glennsarti what's the earliest branch this should be targeted at?

**Comment by Iristyle** [comment]
This change will be backwards compatible with older Puppets, so the course of action depends on release plans I think.  This could plausibly be a `1.1.3` or `1.2.0` that maintains the same compatibility that it currently does.

There is another ticket that needs to be tackled for Puppet 5 that *will* break backwards compatibility - https://tickets.puppetlabs.com/browse/MODULES-3093.  It will require a major version bump to ACL 2.0 and will require a minimum Puppet version of 4.4 I believe.

**Comment by glennsarti** [comment]
@joshcooper I'm not the best person to answer the targetting question.

**Comment by glennsarti** [comment]
From conversation.  This should target `master`

**Pull request merged**
