### PR TITLE
(MODULES-5978) convert acceptance tests to rspec

### PR DESCRIPTION
**Pull request by ThoughtCrhyme**

### CODE REVIEW

**Comment by Iristyle** [comment]
Would be helpful to have the invocation here as well...  is this it?

```
bundle exec rake beaker
```

**Comment by glennsarti** [comment]
Wow that's a lot of files changed!

**Comment by ThoughtCrhyme** [comment]
@glennsarti yeah, I know... it's insanity... we could probably do another pass and rip out some of these tests too.

**Comment by ThoughtCrhyme** [comment]
@michaeltlombardi squashed and rebased master onto this branch.

**Comment by michaeltlombardi** [comment]
Ship It

**Pull request merged**
