### PR TITLE
(MODULES-9293) Update pdk template and re-enable rubocop

### PR DESCRIPTION
**Pull request by eimlav**

### CODE REVIEW

**Comment by tphoney** [comment]
i would also wait for a review from @ThoughtCrhyme @RandomNoun7 or @michaeltlombardi

**Comment by eimlav** [comment]
@tphoney adhoc ran successfully

Screen Shot 2019-06-27 at 13 27 59

**Comment by RandomNoun7** [comment]
I'm ready to merge this one. It just needs a rebase and I'll smash the button.

**Comment by eimlav** [comment]
@RandomNoun7 rebased and ready for merge 👍

**Pull request merged**
